name: temp_package_name
description: temp_package_description

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  get_it: ^7.7.0
  easy_localization: ^3.0.7
  go_router: ^14.2.7

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  jwt_decode: ^0.3.1
  connectivity_plus: ^6.0.5
  hive: ^2.2.3
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_keyboard_visibility: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  file: ^7.0.0
  url_strategy: ^0.3.0
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.4.1
  dotted_border: ^2.1.0
  intl: ^0.18.1
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  universal_html: ^2.2.4
  sentry_flutter: ^8.9.0

  internal_core: 
    path: internal_libs/core
  internal_network: 
    path: internal_libs/network

dependency_overrides:
  http: ^1.1.0
  intl: ^0.18.1
  js: ^0.7.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
